# Generated by Django 5.2.5 on 2025-09-04 12:36

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Уникальный идентификатор категории в URL', max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['created_at'], name='catalog_cat_created_ab7416_idx'), models.Index(fields=['updated_at'], name='catalog_cat_updated_2ec468_idx'), models.Index(django.db.models.functions.text.Lower('name'), name='category_name_lower_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена', max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='На складе')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['price'], name='catalog_pro_price_2d2a4c_idx'), models.Index(fields=['category', 'is_active', '-created_at'], name='catalog_pro_categor_c7565e_idx'), models.Index(django.db.models.functions.text.Lower('name'), name='product_name_lower_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0'), models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_gte_0')],
            },
        ),
    ]
